import type { Metadata } from "next";  

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-red-500">
      {children}
    </main>
  );
}
